import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../Components/themeProvider";
import Navbar from "../Components/Navbar";



export const metadata: Metadata = {
  title: "Mehadi-hasan-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
